image: ghcr.io/felixlohmeier/javafx-maven:latest

stages:
  - clean
  - package

before_script:
  - echo "Iniciando pipeline Spring Boot"

clean:
  stage: clean
  script:
    - mvn clean 

package:
  stage: package
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/jfx/native/*.exe