image: maven:3.6.3-jdk-8

variables:
  MAVEN_VERSION: "3.6.3"

stages:
  - clean
  - package

before_script:
  - echo "Iniciando pipeline Spring Boot"
  - echo $MAVEN_VERSION
  - echo $MAVEN_HOME
  - echo $JAVA_HOME

clean:
  stage: clean
  script:
    - mvn clean 

package:
  stage: package
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/jfx/native/*.exe