variables:
  MAVEN_VERSION: "3.9.9"
  MAVEN_HOME: "C:\\Program Files\\Apache\\Maven\\apache-maven-3.9.9"
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0_51"

stages:
  - check
  - clean
  - package
  - deploy

before_script:
  - $env:PATH="$env:JAVA_HOME\bin;$env:MAVEN_HOME\bin;$env:PATH"
  - java -version
  - mvn -version

check:
  tags:
    - Shell-Maven
  stage: check
  script:
    - echo "Verificações básicas executadas com sucesso"

clean:
  tags:
    - Shell-Maven
  stage: clean
  script:
    - mvn clean 

package:
  tags:
    - Shell-Maven
  stage: package
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/jfx/native/*.exe

deploy:
  tags:
    - Shell-Maven
  stage: deploy
  script:
    - echo "Implantação do aplicativo aqui"